services:

  backend:
    environment:
      APP_UVICORN: '{"host": "0.0.0.0", "port": 8000}'
      APP_PG: '{"host": "postgres"}'
      APP_REDIS: '{"host": "redis" }'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      -mysql
      -redis
    ports:
      -8000:8000

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: NewPassword123!
      MYSQL_DATABASE: link_service
      MYSQL_USER: root
      MYSQL_PASSWORD: NewPassword123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
          -
  redis:
    image: redis:7.2.3-bookworm
    restart: always
    labels:
      - "autoheal=true"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/redis/:/data
    ports:
      # TODO remove in production
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
